name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      max-parallel: 3
      matrix:
        php:
          - 7.2
          - 7.3
          - 7.4
          - 8.0
          - 8.1
        composer: 
          - 2  
    name: Test - php:${{ matrix.php }}; composer:${{ matrix.composer }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, gd, pdo_mysql, json, mbstring, pcre, session
          ini-values: post_max_size=256M
          coverage: none
          tools: composer:v${{ matrix.composer }}
      - name: Composer validate
        run: composer validate --strict --no-check-lock
      - name: Install Composer dependencies (with dev)
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Install Composer dependencies (without dev)
        run: composer install --no-progress --no-dev --no-suggest --prefer-dist --optimize-autoloader
